# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /class/classes/mslan002/final-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /class/classes/mslan002/final-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/mslan002/final-project/CMakeFiles /class/classes/mslan002/final-project/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/mslan002/final-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

board.o: board.cpp.o

.PHONY : board.o

# target to build an object file
board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/board.cpp.o
.PHONY : board.cpp.o

board.i: board.cpp.i

.PHONY : board.i

# target to preprocess a source file
board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/board.cpp.i
.PHONY : board.cpp.i

board.s: board.cpp.s

.PHONY : board.s

# target to generate assembly for a file
board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/board.cpp.s
.PHONY : board.cpp.s

moveBishop.o: moveBishop.cpp.o

.PHONY : moveBishop.o

# target to build an object file
moveBishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBishop.cpp.o
.PHONY : moveBishop.cpp.o

moveBishop.i: moveBishop.cpp.i

.PHONY : moveBishop.i

# target to preprocess a source file
moveBishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBishop.cpp.i
.PHONY : moveBishop.cpp.i

moveBishop.s: moveBishop.cpp.s

.PHONY : moveBishop.s

# target to generate assembly for a file
moveBishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBishop.cpp.s
.PHONY : moveBishop.cpp.s

moveBlackPawn.o: moveBlackPawn.cpp.o

.PHONY : moveBlackPawn.o

# target to build an object file
moveBlackPawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBlackPawn.cpp.o
.PHONY : moveBlackPawn.cpp.o

moveBlackPawn.i: moveBlackPawn.cpp.i

.PHONY : moveBlackPawn.i

# target to preprocess a source file
moveBlackPawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBlackPawn.cpp.i
.PHONY : moveBlackPawn.cpp.i

moveBlackPawn.s: moveBlackPawn.cpp.s

.PHONY : moveBlackPawn.s

# target to generate assembly for a file
moveBlackPawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveBlackPawn.cpp.s
.PHONY : moveBlackPawn.cpp.s

moveFactory.o: moveFactory.cpp.o

.PHONY : moveFactory.o

# target to build an object file
moveFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveFactory.cpp.o
.PHONY : moveFactory.cpp.o

moveFactory.i: moveFactory.cpp.i

.PHONY : moveFactory.i

# target to preprocess a source file
moveFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveFactory.cpp.i
.PHONY : moveFactory.cpp.i

moveFactory.s: moveFactory.cpp.s

.PHONY : moveFactory.s

# target to generate assembly for a file
moveFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveFactory.cpp.s
.PHONY : moveFactory.cpp.s

moveKing.o: moveKing.cpp.o

.PHONY : moveKing.o

# target to build an object file
moveKing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKing.cpp.o
.PHONY : moveKing.cpp.o

moveKing.i: moveKing.cpp.i

.PHONY : moveKing.i

# target to preprocess a source file
moveKing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKing.cpp.i
.PHONY : moveKing.cpp.i

moveKing.s: moveKing.cpp.s

.PHONY : moveKing.s

# target to generate assembly for a file
moveKing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKing.cpp.s
.PHONY : moveKing.cpp.s

moveKnight.o: moveKnight.cpp.o

.PHONY : moveKnight.o

# target to build an object file
moveKnight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKnight.cpp.o
.PHONY : moveKnight.cpp.o

moveKnight.i: moveKnight.cpp.i

.PHONY : moveKnight.i

# target to preprocess a source file
moveKnight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKnight.cpp.i
.PHONY : moveKnight.cpp.i

moveKnight.s: moveKnight.cpp.s

.PHONY : moveKnight.s

# target to generate assembly for a file
moveKnight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveKnight.cpp.s
.PHONY : moveKnight.cpp.s

moveQueen.o: moveQueen.cpp.o

.PHONY : moveQueen.o

# target to build an object file
moveQueen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveQueen.cpp.o
.PHONY : moveQueen.cpp.o

moveQueen.i: moveQueen.cpp.i

.PHONY : moveQueen.i

# target to preprocess a source file
moveQueen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveQueen.cpp.i
.PHONY : moveQueen.cpp.i

moveQueen.s: moveQueen.cpp.s

.PHONY : moveQueen.s

# target to generate assembly for a file
moveQueen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveQueen.cpp.s
.PHONY : moveQueen.cpp.s

moveRook.o: moveRook.cpp.o

.PHONY : moveRook.o

# target to build an object file
moveRook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveRook.cpp.o
.PHONY : moveRook.cpp.o

moveRook.i: moveRook.cpp.i

.PHONY : moveRook.i

# target to preprocess a source file
moveRook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveRook.cpp.i
.PHONY : moveRook.cpp.i

moveRook.s: moveRook.cpp.s

.PHONY : moveRook.s

# target to generate assembly for a file
moveRook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveRook.cpp.s
.PHONY : moveRook.cpp.s

moveWhitePawn.o: moveWhitePawn.cpp.o

.PHONY : moveWhitePawn.o

# target to build an object file
moveWhitePawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveWhitePawn.cpp.o
.PHONY : moveWhitePawn.cpp.o

moveWhitePawn.i: moveWhitePawn.cpp.i

.PHONY : moveWhitePawn.i

# target to preprocess a source file
moveWhitePawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveWhitePawn.cpp.i
.PHONY : moveWhitePawn.cpp.i

moveWhitePawn.s: moveWhitePawn.cpp.s

.PHONY : moveWhitePawn.s

# target to generate assembly for a file
moveWhitePawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/moveWhitePawn.cpp.s
.PHONY : moveWhitePawn.cpp.s

piece.o: piece.cpp.o

.PHONY : piece.o

# target to build an object file
piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/piece.cpp.o
.PHONY : piece.cpp.o

piece.i: piece.cpp.i

.PHONY : piece.i

# target to preprocess a source file
piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/piece.cpp.i
.PHONY : piece.cpp.i

piece.s: piece.cpp.s

.PHONY : piece.s

# target to generate assembly for a file
piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/piece.cpp.s
.PHONY : piece.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/player.cpp.s
.PHONY : player.cpp.s

tests/unit_test.o: tests/unit_test.cpp.o

.PHONY : tests/unit_test.o

# target to build an object file
tests/unit_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/unit_test.cpp.o
.PHONY : tests/unit_test.cpp.o

tests/unit_test.i: tests/unit_test.cpp.i

.PHONY : tests/unit_test.i

# target to preprocess a source file
tests/unit_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/unit_test.cpp.i
.PHONY : tests/unit_test.cpp.i

tests/unit_test.s: tests/unit_test.cpp.s

.PHONY : tests/unit_test.s

# target to generate assembly for a file
tests/unit_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/unit_test.cpp.s
.PHONY : tests/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... moveBishop.o"
	@echo "... moveBishop.i"
	@echo "... moveBishop.s"
	@echo "... moveBlackPawn.o"
	@echo "... moveBlackPawn.i"
	@echo "... moveBlackPawn.s"
	@echo "... moveFactory.o"
	@echo "... moveFactory.i"
	@echo "... moveFactory.s"
	@echo "... moveKing.o"
	@echo "... moveKing.i"
	@echo "... moveKing.s"
	@echo "... moveKnight.o"
	@echo "... moveKnight.i"
	@echo "... moveKnight.s"
	@echo "... moveQueen.o"
	@echo "... moveQueen.i"
	@echo "... moveQueen.s"
	@echo "... moveRook.o"
	@echo "... moveRook.i"
	@echo "... moveRook.s"
	@echo "... moveWhitePawn.o"
	@echo "... moveWhitePawn.i"
	@echo "... moveWhitePawn.s"
	@echo "... piece.o"
	@echo "... piece.i"
	@echo "... piece.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... tests/unit_test.o"
	@echo "... tests/unit_test.i"
	@echo "... tests/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

